### ISSUE TITLE
Make footer visible

### ISSUE THREAD

**Issue by sandeep-v1404** [sandeep-v1404/ReactWeatherApp#10]

**Comment by Akku2016** [comment]
can i do

**Comment by sandeep-v1404** [comment]
Yes @Akku2016

**Comment by Akku2016** [comment]
hi i am newbie here , i have to create new file else which file i can follow

**Comment by sandeep-v1404** [comment]
You know React? @Akku2016

**Comment by Akku2016** [comment]
Yes I know

**Comment by Akku2016** [comment]
actually i want to ask you mentioned "add footer visible" this one where I can do 👎 
1) i have to create new file 
2)new component
3)little bit idea give me

**Comment by sandeep-v1404** [comment]
@Akku2016  Already footer is there, but it's visible only when we search for a city in the application. But even without searching it should be visible.

**Comment by sandeep-v1404** [comment]
@Akku2016 Someone has already fixed it. You can use the application and check for new bugs or features you want to add.
